# Generated by Django 5.0 on 2024-01-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listItems', models.CharField(max_length=40)),
                ('status', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
