# Generated by Django 5.0 on 2024-01-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='incompleted',
            field=models.IntegerField(default=0),
        ),
    ]
